//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Domain.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam: TrackedEntity
    {
        public Exam()
        {
            this.ExamQuestions = new HashSet<Question>();
        }
    
        public int Id { get; set; }
        public string ExamName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<decimal> ExamDuration { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ExamStartDate { get; set; }
    
        public virtual ICollection<Question> ExamQuestions { get; set; }

        public string ApplicationUserId { get; set; }
        public ApplicationUser CreationBy { get; set; }
    }
}
