//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Domain.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.ExamQuestions = new HashSet<Exam>();
        }

        public int Id { get; set; }
        public string Question1 { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Exam> ExamQuestions { get; set; }
    }
}
